services:

  user-profile-service:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: user-profile-service

    ports:
      - "5002:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userprofiledb;Username=postgres;Password=postgres"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - .:/src

    networks:
      - userprofile-network


  postgres:
    image: postgres:16

    container_name: user-profile-postgres

    environment:
      POSTGRES_DB: userprofiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userprofiledb"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - userprofile-network


networks:
  userprofile-network:
    driver: bridge


volumes:
  postgres_data: