FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "watch", "run", "--project", "AuthService.Api/AuthService.Api.csproj", "--urls", "http://+:8080"]