services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: user-profile-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql-backups:/var/opt/mssql/backup

    networks:
      - userprofile-network

volumes:
  sqlserver_data:

networks:
  userprofile-network:
    driver: bridge
